### ISSUE TITLE
API key linting only works after saving twice

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/vscode-stripe#67] opened 2020-11-17 02:14 UTC
**Actual:**
seems like I need to save my file twice to get Stripe to lint it (for example to show error with hardcoded api key)

**Expected**
API key linting works on first save.

**Comment by vcheung-stripe** [comment] 2021-04-13 18:13
I can't reproduce this anymore. Closing.

**Closed by vcheung-stripe** 2021-04-13 18:13 UTC
Labels: blocked, bug
