### ISSUE TITLE
Extension causes high cpu load; halts loading of other extensions while activating

### ISSUE THREAD

**Issue by neilraya** [stripe/vscode-stripe#167] opened 2021-02-07 22:38 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-stripe`
- Extension Version: `1.7.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning: `c:\Users\neilr\AppData\Local\Temp\stripe.vscode-stripe-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

- Love the extension, many excellent features that make testing Stripe a breeze. It would great if it could be optimized (load time), however considering the large functionality I understand if it must be heavy

- I've attached the log file below

[stripe.vscode-stripe-unresponsive.cpuprofile.txt](https://github.com/stripe/vscode-stripe/files/5939952/stripe.vscode-stripe-unresponsive.cpuprofile.txt)

**Comment by vcheung-stripe** [comment] 2021-03-18 19:45
Hello @neilraya, thanks for the report! We took some time to look through your profile and made a profile of our own, but we're having a little bit of trouble finding evidence of large blockages caused by vscode-stripe. Would you be willing to spell out in a little bit more detail how you came to the conclusion that vscode-stripe is suffering from slow load times, and what the load times are?

**Comment by etsai-stripe** [comment] 2021-11-18 19:14
closing this issue because it was not reproducible and user has not responded since issue raised. 
could have been fixed by https://github.com/stripe/vscode-stripe/pull/197
see https://github.com/stripe/vscode-stripe/issues/193 for context

**Closed by etsai-stripe** 2021-11-18 19:14 UTC
